# Generated by Django 4.2.17 on 2025-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('emergency', 'Emergency Contact'), ('primary_provider', 'Primary Care Provider'), ('pharmacy', 'Pharmacy'), ('home_aid', 'Home Aid'), ('home_care', 'Home Care'), ('other', 'Other')], max_length=30),
        ),
    ]
