# Generated by Django 4.2.17 on 2025-05-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_enrollment_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='change_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('disenrollment', 'Disenrollment')], max_length=20),
        ),
    ]
