# Generated by Django 4.2.17 on 2025-05-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_enrollment_change_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='new_mltc',
            new_name='mltc',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='old_mltc',
        ),
    ]
