# Generated by Django 4.2.17 on 2025-05-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_enrollment_change_type_enrollment_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='mltc',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='change_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('transfer', 'Transfer'), ('disenrollment', 'Disenrollment')], default='enrollment', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='new_mltc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_enrollments', to='core.mltc'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='old_mltc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_enrollments', to='core.mltc'),
        ),
    ]
