# Generated by Django 4.2.17 on 2025-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_enrollment_enrollment_remove_enrollment_mltc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mltc',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
