# Generated by Django 4.2.17 on 2025-05-18 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mltc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
