# Generated by Django 4.2.17 on 2025-06-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mltc_options_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
