# Generated by Django 4.2.17 on 2025-05-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_enrollment_change_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-change_date']},
        ),
    ]
