# Generated by Django 4.2.17 on 2025-05-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_enrollment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
