# Generated by Django 4.2.17 on 2025-05-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_uploaded_at_file_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
