# Generated by Django 4.2.17 on 2025-05-20 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_absence_options_alter_authorization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='change_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='SADC',
        ),
    ]
