# Generated by Django 4.2.17 on 2025-06-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_absence_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='mltc_auth_id',
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='sdc_code',
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='trans_code',
        ),
        migrations.CreateModel(
            name='AuthorizationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('sdc', 'SDC'), ('transportation', 'Transportation')], max_length=20)),
                ('auth_id', models.CharField(max_length=255, null=True)),
                ('service_code', models.CharField(blank=True, max_length=255, null=True)),
                ('service_units', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.authorization')),
            ],
            options={
                'unique_together': {('authorization', 'service')},
            },
        ),
    ]
