# Generated by Django 4.2.17 on 2025-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_enrollment_change_date_delete_sadc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sadc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
