# Generated by Django 4.2.17 on 2025-06-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_authorization_mltc_auth_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizationservice',
            old_name='service',
            new_name='service_type',
        ),
        migrations.AlterUniqueTogether(
            name='authorizationservice',
            unique_together={('authorization', 'service_type')},
        ),
    ]
