# Generated by Django 4.2.17 on 2025-06-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_service_authorizationservice_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='cm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorization',
            name='cm_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='authorization',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
