# Generated by Django 4.2.17 on 2025-05-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_absence_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='core.member'),
        ),
    ]
