# Generated by Django 4.2.17 on 2025-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_member_address_delete_address_delete_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mltc',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
