# Generated by Django 4.2.17 on 2025-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mltc_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mltc',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
