# Generated by Django 4.2.17 on 2025-06-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mltc_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mltc',
            options={'ordering': ['active', 'name']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('emergency_contact', 'Emergency Contact'), ('primary_care_provider', 'Primary Care Provider'), ('pharmacy', 'Pharmacy'), ('home_aid', 'Home Aid'), ('home_care', 'Home Care'), ('other', 'Other')], max_length=30),
        ),
    ]
