# Generated by Django 4.2.17 on 2025-06-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_member_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nickname',
            new_name='alt_name',
        ),
    ]
