# Generated by Django 4.2.17 on 2025-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_nickname_member_alt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('hospital', 'Hospital'), ('personal', 'Personal'), ('assessment', 'Assessment'), ('other', 'Other')], max_length=20),
        ),
    ]
