# Generated by Django 4.2.17 on 2025-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_absence_absence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
