# Generated by Django 4.2.17 on 2025-06-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_authorization_cm_name_authorization_cm_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='expiration_date',
        ),
    ]
