# Generated by Django 4.2.17 on 2025-06-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_member_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_by',
        ),
    ]
