# Generated by Django 4.2.17 on 2025-06-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_member_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.language'),
        ),
    ]
