# Generated by Django 4.2.17 on 2025-06-19 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_member_sadc'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='sadc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.sadc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mltc',
            name='sadc',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='mltcs', to='core.sadc'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('sadc', 'name')},
        ),
    ]
