# Generated by Django 4.2.17 on 2025-06-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_language_sadc_mltc_sadc_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mltc',
            unique_together={('sadc', 'name')},
        ),
    ]
