# Generated by Django 4.2.17 on 2025-06-19 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_mltc_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadc',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sadc',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sadc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sadc',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sadc',
            name='npi',
            field=models.CharField(blank=True, help_text='National Provider Identifier', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sadc',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sadc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
