# Generated by Django 4.2.17 on 2025-06-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('user', '0010_alter_user_allowed_mltcs_alter_user_sadc'),
        ('core', '0028_sadc_attendance_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mltc',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mltc',
            name='sadc',
        ),
        migrations.AlterField(
            model_name='authorization',
            name='mltc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.mltc'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='new_mltc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_enrollments', to='tenant.mltc'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='old_mltc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_enrollments', to='tenant.mltc'),
        ),
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenant.language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sadc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenant.sadc'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='MLTC',
        ),
        migrations.DeleteModel(
            name='Sadc',
        ),
    ]
