# Generated by Django 4.2.17 on 2025-06-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_mltc_unique_together_remove_mltc_sadc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-change_date', '-created_at']},
        ),
    ]
