# Generated by Django 4.2.17 on 2025-06-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_enrollment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
