# Generated by Django 4.2.17 on 2025-06-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_absence_note_alter_authorization_cm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=220, null=True),
        ),
    ]
