# Generated by Django 4.2.17 on 2025-06-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_member_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
