# Generated by Django 4.2.17 on 2025-07-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_delete_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
