# Generated by Django 4.2.17 on 2025-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_absence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationservice',
            name='auth_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationservice',
            name='service_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
