# Generated by Django 4.2.17 on 2025-07-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_gift'),
        ('core', '0037_gift_giftmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifted', to='tenant.gift')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='core.member')),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('gift', 'member')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='giftmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='giftmember',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='giftmember',
            name='member',
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.DeleteModel(
            name='GiftMember',
        ),
    ]
