# Generated by Django 4.2.17 on 2025-07-16 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0038_gifted_alter_giftmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-start_date', '-end_date'], 'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.AlterModelOptions(
            name='authorizationservice',
            options={'verbose_name': 'Authorization', 'verbose_name_plural': 'Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['contact_type'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='gifted',
            options={'ordering': ['-received_at'], 'verbose_name': 'Gifted', 'verbose_name_plural': 'Gifted'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['sadc_member_id'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RemoveField(
            model_name='absence',
            name='time',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='user',
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('absence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.absence')),
                ('time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
            bases=('core.absence',),
        ),
    ]
