# Generated by Django 4.2.17 on 2025-07-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_absence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifted',
            name='note',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
