# Generated by Django 4.2.17 on 2025-07-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_gifted_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifted',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
