# Generated by Django 4.2.17 on 2025-07-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_gifted_received_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gifted',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gifted', 'verbose_name_plural': 'Gifted'},
        ),
        migrations.RemoveField(
            model_name='gifted',
            name='received_at',
        ),
        migrations.AddField(
            model_name='gifted',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
