# Generated by Django 4.2.17 on 2025-07-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_gifted_options_remove_gifted_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifted',
            name='gift',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
