# Generated by Django 4.2.17 on 2025-07-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_gifted_gift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gifted',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gifted',
            name='gift_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gifted',
            name='gift_name',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gifted',
            unique_together={('gift_id', 'member')},
        ),
        migrations.RemoveField(
            model_name='gifted',
            name='gift',
        ),
    ]
