# Generated by Django 4.2.17 on 2025-07-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_gifted_unique_together_gifted_gift_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifted',
            old_name='gift_name',
            new_name='name',
        ),
    ]
