# Generated by Django 4.2.17 on 2025-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_rename_gift_name_gifted_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='authorization',
            constraint=models.UniqueConstraint(fields=('member', 'start_date'), name='unique_member_start_date'),
        ),
    ]
