# Generated by Django 4.2.17 on 2025-09-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_authorization_unique_member_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
