# Generated by Django 4.2.17 on 2025-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_absence_file_alter_authorization_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
