# Generated by Django 4.2.17 on 2025-09-11 18:20

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='alt_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=encrypted_model_fields.fields.EncryptedDateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='medicaid',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
