# Generated by Django 4.2.17 on 2025-09-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_member_address_alter_member_alt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['birth_month', 'birth_day'], name='core_member_birth_m_66fbbf_idx'),
        ),
    ]
