# Generated by Django 4.2.17 on 2025-09-13 15:18

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_member_birth_day_member_birth_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='mltc_member_id',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship_type',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, choices=[('husband', 'Husband'), ('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend'), ('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], help_text='Only used if this if contact type is emergency', null=True),
        ),
    ]
