# Generated by Django 4.2.17 on 2025-09-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_authorization_mltc_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('husband', 'Husband'), ('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend'), ('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], help_text='Only used if this if contact type is emergency', max_length=20, null=True),
        ),
    ]
