# Generated by Django 4.2.17 on 2025-05-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='action',
            new_name='action_type',
        ),
    ]
