# Generated by Django 4.2.17 on 2025-05-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='member',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
