# Generated by Django 4.2.17 on 2025-05-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_contact_type'),
        ('audit', '0005_auditlog_member_auditlog_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='member_name',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.member'),
        ),
    ]
