# Generated by Django 4.2.17 on 2025-07-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-change_date', '-created_at'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
    ]
