# Generated by Django 4.2.17 on 2025-09-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_alter_auditlog_options_alter_enrollment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='object_display',
            new_name='object_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='member',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='new_mltc',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='old_mltc',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='member_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='member_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='new_mltc_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='new_mltc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='old_mltc_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='old_mltc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
