# Generated by Django 4.2.17 on 2025-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_rename_object_display_auditlog_object_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='member_id',
            field=models.PositiveIntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='member_name',
            field=models.CharField(default=19, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_name',
            field=models.CharField(default=19, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.PositiveIntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='member_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='member_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='new_mltc_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='old_mltc_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
