# Generated by Django 4.2.17 on 2025-09-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_alter_auditlog_member_id_alter_auditlog_member_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='new_mltc_name',
            new_name='new_mltc',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='old_mltc_name',
            new_name='old_mltc',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='new_mltc_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='old_mltc_id',
        ),
    ]
