# Generated by Django 4.2.17 on 2025-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_rename_new_mltc_name_enrollment_new_mltc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='member_alt_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='member_alt_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
