# Generated by Django 4.2.17 on 2025-06-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sadc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('npi', models.CharField(blank=True, help_text='National Provider Identifier', max_length=10, null=True, unique=True)),
                ('attendance_template', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dx_codes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('sadc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mltcs', to='tenant.sadc')),
            ],
            options={
                'ordering': ['active', 'name'],
                'unique_together': {('sadc', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sadc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='tenant.sadc')),
            ],
            options={
                'unique_together': {('sadc', 'name')},
            },
        ),
    ]
