# Generated by Django 4.2.17 on 2025-06-21 01:42

import backend.apps.tenant.models.sadc_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadc',
            name='language',
            field=models.JSONField(default=backend.apps.tenant.models.sadc_model.default_language),
        ),
    ]
