# Generated by Django 4.2.17 on 2025-06-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_member_language'),
        ('tenant', '0002_sadc_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
