# Generated by Django 4.2.17 on 2025-06-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_delete_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sadc',
            old_name='language',
            new_name='languages',
        ),
    ]
