# Generated by Django 4.2.17 on 2025-06-21 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_rename_language_sadc_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='mltc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mltc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
