# Generated by Django 4.2.17 on 2025-06-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_mltc_created_at_mltc_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('members', 'Members'), ('birthdays', 'Birthdays'), ('absences', 'Absences'), ('assessments', 'Assessments'), ('enrollments', 'Enrollments')], max_length=20)),
                ('file', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sadc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.sadc')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('sadc', 'date', 'type')},
            },
        ),
    ]
