# Generated by Django 4.2.17 on 2025-06-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mltc',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sadc',
            name='address',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='sadc',
            name='email',
            field=models.EmailField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sadc',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sadc',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
