# Generated by Django 4.2.17 on 2025-07-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_alter_mltc_name_alter_sadc_address_alter_sadc_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
