# Generated by Django 4.2.17 on 2025-07-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_gift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
    ]
