# Generated by Django 4.2.17 on 2025-07-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_gift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['expires_at', 'created_at'], 'verbose_name': 'Gift', 'verbose_name_plural': 'Gifts'},
        ),
        migrations.AlterModelOptions(
            name='mltc',
            options={'ordering': ['active', 'name'], 'verbose_name': 'MLTC', 'verbose_name_plural': 'MLTCs'},
        ),
        migrations.AlterModelOptions(
            name='sadc',
            options={'verbose_name': 'SADC', 'verbose_name_plural': 'SADCs'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-date'], 'verbose_name': 'Snapshot', 'verbose_name_plural': 'Snapshots'},
        ),
    ]
