# Generated by Django 4.2.17 on 2025-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_alter_gift_options_alter_mltc_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
