# Generated by Django 4.2.17 on 2025-07-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0014_gift_birth_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='expires_delete',
            field=models.BooleanField(default=False),
        ),
    ]
