# Generated by Django 4.2.17 on 2025-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0015_gift_expires_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='type',
            field=models.CharField(choices=[('members', 'Members'), ('birthdays', 'Birthdays'), ('absences', 'Absences'), ('assessments', 'Assessments'), ('enrollments', 'Enrollments'), ('gifts', 'Gifts')], max_length=20),
        ),
    ]
