# Generated by Django 4.2.17 on 2025-09-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0016_alter_snapshot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
