# Generated by Django 4.2.17 on 2025-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_remove_auditlog_member_name_alter_auditlog_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='object_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
