# Generated by Django 4.2.17 on 2025-05-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sadc'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffUser',
            new_name='User',
        ),
    ]
