# Generated by Django 4.2.17 on 2025-05-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_staffuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_type',
        ),
    ]
