# Generated by Django 4.2.17 on 2025-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_file_date'),
        ('user', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_mltcs',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.mltc'),
        ),
    ]
