# Generated by Django 4.2.17 on 2025-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_allowed_mltcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_mltcs',
        ),
        migrations.AddField(
            model_name='user',
            name='global_access',
            field=models.BooleanField(default=False, help_text='True > Can edit all members. False > Can only edit members created by self'),
        ),
    ]
