# Generated by Django 4.2.17 on 2025-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_global_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='global_access',
            field=models.BooleanField(default=True, help_text='True: Can edit all members. False: Can only edit members created by self'),
        ),
    ]
