# Generated by Django 4.2.17 on 2025-06-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_global_access_user_allowed_mltcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_snapshots',
            field=models.BooleanField(default=False),
        ),
    ]
