# Generated by Django 4.2.17 on 2025-05-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_role_type_user_is_org_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['is_org_admin', 'name']},
        ),
    ]
