# Generated by Django 4.2.17 on 2025-06-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('user', '0009_user_view_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_mltcs',
            field=models.ManyToManyField(blank=True, related_name='users', to='tenant.mltc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sadc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenant.sadc'),
        ),
    ]
