# Generated by Django 4.2.17 on 2025-07-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['is_org_admin', 'name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
